spring:
  profiles.active: dev
---
spring:
 # everything that follows belongs to the devel environment
  profiles: dev
  name: development

demo:
  locators: localhost[10334]
---
spring:
 # everything that follows belongs to the prod environment
 profiles: prod
 name: production

demo:
  locators: localhost[10334]


---
spring:
  # everything that follows belongs to the unit-test environment
  profiles: unit-test
  name: unit test name

demo:
  locators: localhost[10334]
